[metadata]
name = volttron
version = 9.0.4
description = Agent Execution Platform
author = Volttron Team
author_email = volttron@pnnl.gov
url = https://github.com/VOLTTRON/volttron

[options]
packages = find:
python_requires = >=3.10
install_requires =
    gevent==24.2.1
    grequests==0.7.0
    requests==2.31.0
    idna<3,>=2.5
    ply==3.11
    psutil==5.9.1
    python-dateutil==2.8.2
    pytz==2022.1
    PyYAML==6.0
    setuptools>=40.0.0,<=70.0.0
    tzlocal==2.1
    cryptography==37.0.4
    watchdog<5.0
    watchdog-gevent==0.1.1
    deprecated==1.2.14

[options.extras_require]
testing =
    mock==4.0.3
    pytest==7.1.2
    pytest-timeout==2.1.0
    pytest-rerunfailures==10.2
    websocket-client==1.2.2
    deepdiff==5.8.1
    docker==5.0.3
    pytest-asyncio==0.19.0

[options.entry_points]
console_scripts =
    volttron = volttron.platform.main:_main
    volttron-ctl = volttron.platform.control.control_parser:_main
    volttron-pkg = volttron.platform.packaging:_main
    volttron-cfg = volttron.platform.config:_main
    vctl = volttron.platform.control.control_parser:_main
    vpkg = volttron.platform.packaging:_main
    vcfg = volttron.platform.config:_main
    volttron-upgrade = volttron.platform.upgrade.upgrade_volttron:_main